# Generated by Django 4.1.2 on 2022-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=True),
        ),
    ]
