# Generated by Django 4.1.2 on 2022-11-04 13:26

import Blog.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_user_bio_remove_user_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/user_image/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=Blog.fields.CaseInsensitiveCharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='deleterequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=Blog.fields.CaseInsensitiveCharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
