# Generated by Django 4.1.2 on 2022-11-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_user_bio_user_user_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleterequest',
            name='delete_request',
        ),
    ]
