# Generated by Django 4.1.2 on 2022-11-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_remove_deleterequest_delete_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteRequest',
        ),
    ]
